#!/usr/bin/env bash
cd /tmp
apt-get update
apt-get install --yes libsqlite3-dev zlib1g zlib1g-dev libsdl2-dev libsdl2-image-dev libguichan-dev
wget -q -O- "http://kat5200.jillybunch.com/downloads/kat5200-0.7.1.tar.gz" | tar -xvz --strip-components=1
./configure
make
make install

if [ ! -d "/home/pi/RetroPie/roms/atari5200" ]; then
  mkdir /home/pi/RetroPie/roms/atari5200
fi

if [ -f "/home/pi/RetroPie/BIOS/5200.ROM" ]
then
	echo "Bios found."
else
	echo "Bios not found."
  // ################# is wget bios allowed ?
fi

if [ ! -d "/opt/retropie/configs/atari5200" ]; then
  mkdir /opt/retropie/configs/atari5200
fi

if [ -f "/opt/retropie/configs/atari5200/default_config.db3" ]
then
	echo "Default configuration file already present."
  // #################  present choice, rename or overwrite it ?
else
	echo "Default configuration file not found."
  // #################  cd /opt/retropie/configs/atari5200/
  // #################  wget "whatever"
  // #################  cd /tmp
fi

if [ -f "/opt/retropie/configs/atari5200/emulators.cfg" ]
then
	echo "Emulators file already present."
  // maybe use sed to alter ?
else
	echo "Emulator file not found."
  //cat << EOF > /opt/retropie/configs/atari5200/emulators.cfg
kat5200 = "cp /opt/retropie/configs/atari5200/default_config.db3 /home/pi/.kat5200/kat5200.db3 ;/opt/retropie/emulators/retroarch/bin/retroarch -L /usr/local/bin/kat5200 %ROM%"
default = "kat5200".
EOF
fi
